steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t europe-west1-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image-ludo:tag1 .
  automapSubstitutions: true
images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image-ludo:tag1'